spring:
  datasource:
    name: cfdb
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /db

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/docs/
      cache:
        cachecontrol:
          no-cache: true
server:
  port: 9090
logging:
  level:
    root: info
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger.html