spring:
  datasource:
    generate-unique-name: false
    username: soluwafemi
    password: wCAtkGmAtilCQo6uIvcCUyHYtzAqgKbe
    url: jdbc:postgres://dpg-cg23prl269vfsnufs1k0-a.oregon-postgres.render.com:5432/product_db_xvsd
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    show-sql: true
server:
  port: 9090
logging:
  level:
    root: info
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger.html